package railway.bangladesh;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import java.sql.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Yusha
 */
public class log_in extends javax.swing.JFrame {

    /**
     * Creates new form log_in
     */
    public log_in() {
        initComponents();
        this.setLocationRelativeTo(null); //center form in the screen
    }
    
    static int send_CustomerId;

    String url = "jdbc:sqlserver://LAPTOP-3GFO49NI\\SQLEXPRESS:1433;databaseName=RailwayBangladesh";
    String sql_user = "sqlyusha";
    String sql_password = "123456789";
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Password_label_login = new javax.swing.JLabel();
        Email_label_login = new javax.swing.JLabel();
        email_login_jtext = new javax.swing.JTextField();
        Showpass_checkbox = new javax.swing.JCheckBox();
        login_button = new javax.swing.JButton();
        signUp_button = new javax.swing.JButton();
        title_login = new javax.swing.JLabel();
        password_login_field = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg 1.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 380, 500);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Password_label_login.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        Password_label_login.setText("Password");
        jPanel1.add(Password_label_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 130, 40));

        Email_label_login.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        Email_label_login.setText("Email");
        jPanel1.add(Email_label_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 130, 40));

        email_login_jtext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        email_login_jtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_login_jtextActionPerformed(evt);
            }
        });
        jPanel1.add(email_login_jtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 350, 50));

        Showpass_checkbox.setBackground(new java.awt.Color(255, 255, 255));
        Showpass_checkbox.setFont(new java.awt.Font("Calisto MT", 0, 13)); // NOI18N
        Showpass_checkbox.setText("Show Password");
        Showpass_checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Showpass_checkboxActionPerformed(evt);
            }
        });
        jPanel1.add(Showpass_checkbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        login_button.setBackground(new java.awt.Color(3, 169, 252));
        login_button.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        login_button.setForeground(new java.awt.Color(255, 255, 255));
        login_button.setText("Log In");
        login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(login_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 170, 50));

        signUp_button.setBackground(new java.awt.Color(3, 169, 252));
        signUp_button.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        signUp_button.setForeground(new java.awt.Color(255, 255, 255));
        signUp_button.setText("Sign Up");
        signUp_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUp_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(signUp_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 170, 50));

        title_login.setBackground(new java.awt.Color(255, 255, 255));
        title_login.setFont(new java.awt.Font("Calisto MT", 1, 40)); // NOI18N
        title_login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_login.setText("Railway Bangladesh");
        jPanel1.add(title_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 40, 370, 60));

        password_login_field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(password_login_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 350, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signUp_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUp_buttonActionPerformed
        this.setVisible(false);
        sign_up ob = new sign_up();
        ob.setVisible(true);
    }//GEN-LAST:event_signUp_buttonActionPerformed

    private void email_login_jtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_login_jtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_login_jtextActionPerformed

    private void login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_buttonActionPerformed
        
        
        
        try {
            
            //If any field is blank
            
            if(email_login_jtext.getText().isEmpty() || password_login_field.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(this, "Username or Password is blank!");
            }
            
            else
            {
                
                String email = email_login_jtext.getText();
                String password = new String(password_login_field.getPassword());
                
                Connection connection = DriverManager.getConnection(url, sql_user, sql_password);
                String sql = "SELECT * FROM LogInUser WHERE Email = '"+email+"' AND User_Password = '"+password+"' ";
                Statement statement = connection.createStatement();
                ResultSet rs = statement.executeQuery(sql);
                
               //if user found in database
                if(rs.next())
                {
                    this.hide();
                    user_home_page ob = new user_home_page();
                    ob.setVisible(true);
                }
                //otherwise incorrect email or password
                else
                {
                    JOptionPane.showMessageDialog(this, "Email or Password is incorrect!");
                    email_login_jtext.setText("");
                    password_login_field.setText("");
                    email_login_jtext.requestFocus();                   
                }
                
                String sql2 = "SELECT * FROM CUSTOMER WHERE Email = '"+email+"' AND CustomerPassword = '"+password+"' ";
                ResultSet rs2 = statement.executeQuery(sql2);
                
                if(rs2.next())
                {
                    send_CustomerId = rs2.getInt("CustomerId");
                }
                
                
            }

        } catch (SQLException e) {
            System.out.println("database connection failed");
            e.printStackTrace();
        }
    }//GEN-LAST:event_login_buttonActionPerformed

    private void Showpass_checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Showpass_checkboxActionPerformed
        //show password checkbox
        if(Showpass_checkbox.isEnabled())
        {
            password_login_field.setEchoChar((char)0);
        }
        
        
    }//GEN-LAST:event_Showpass_checkboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(log_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(log_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(log_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(log_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new log_in().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Email_label_login;
    private javax.swing.JLabel Password_label_login;
    private javax.swing.JCheckBox Showpass_checkbox;
    private javax.swing.JTextField email_login_jtext;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton login_button;
    private javax.swing.JPasswordField password_login_field;
    private javax.swing.JButton signUp_button;
    private javax.swing.JLabel title_login;
    // End of variables declaration//GEN-END:variables
}
