/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package railway.bangladesh;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import static railway.bangladesh.user_home_page.send_train_number;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import java.sql.*;
import java.util.Random;

/**
 *
 * @author Yusha
 */
public class ticket_info extends javax.swing.JFrame {

    /**
     * Creates new form ticket_info
     */
    public ticket_info() {
        initComponents();
        this.setLocationRelativeTo(null); //center form in the screen

        String url = "jdbc:sqlserver://LAPTOP-3GFO49NI\\SQLEXPRESS:1433;databaseName=RailwayBangladesh";
        String sql_user = "sqlyusha";
        String sql_password = "123456789";

        try {

            int train_no = user_home_page.send_train_number;
            String train_number = String.valueOf(train_no);
            String departure_date = user_home_page.send_date;
            Connection connection = DriverManager.getConnection(url, sql_user, sql_password);
            String sql = "SELECT TicketPrice FROM Seats WHERE TrainNumber = '" + train_number + "' AND DepartureDate = '" + departure_date + "' AND SeatType ='AC'";
            Statement statement = connection.createStatement();
            ResultSet rs = statement.executeQuery(sql);

            if (rs.next()) {
                price_ac_label_ticketpage.setText(String.valueOf(rs.getInt("TicketPrice")));
            }

            String sql2 = "SELECT TicketPrice FROM Seats WHERE TrainNumber = '" + train_number + "' AND DepartureDate = '" + departure_date + "' AND SeatType ='NON AC'";

            ResultSet rs2 = statement.executeQuery(sql2);

            if (rs2.next()) {
                price_nonac_label_ticketpage.setText(String.valueOf(rs2.getInt("TicketPrice")));
            }

            String sql3 = "SELECT * FROM Seats WHERE TrainNumber = '" + train_number + "' AND DepartureDate = '" + departure_date + "' AND SeatType ='AC' AND SeatStatus='Available'";
            ResultSet rs3 = statement.executeQuery(sql3);
            while (rs3.next()) {
                seat_number_ac_combo_ticketpage.addItem(rs3.getString("SeatNumber"));
            }

            String sql4 = "SELECT * FROM Seats WHERE TrainNumber = '" + train_number + "' AND DepartureDate = '" + departure_date + "' AND SeatType ='NON AC' AND SeatStatus='Available'";
            ResultSet rs4 = statement.executeQuery(sql4);
            while (rs4.next()) {
                seat_number_nonac_combo_ticketpage.addItem(rs4.getString("SeatNumber"));
            }
            
            

        } catch (SQLException e) {
            System.out.println("database connection failed");
            e.printStackTrace();
        }
    }
    static int total_fare = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        price_nonac_label_ticketpage = new javax.swing.JLabel();
        seat_number_ac_combo_ticketpage = new javax.swing.JComboBox<>();
        seat_number_nonac_combo_ticketpage = new javax.swing.JComboBox<>();
        ticket_page_label = new javax.swing.JLabel();
        total_price_label_ticketpage = new javax.swing.JLabel();
        seat_type_ticketpage = new javax.swing.JLabel();
        generate_ticket_button_ticketpage = new javax.swing.JButton();
        price_ticketpage = new javax.swing.JLabel();
        seat_number_ticketpage = new javax.swing.JLabel();
        total_price_ticketpage = new javax.swing.JLabel();
        price_ac_label_ticketpage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        seat_number_input_jtext = new javax.swing.JTextField();
        ok_button_train_info = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        price_nonac_label_ticketpage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        seat_number_ac_combo_ticketpage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        seat_number_nonac_combo_ticketpage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        ticket_page_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ticket_page_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ticket_page_label.setText("TICKET INFO");

        total_price_label_ticketpage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        seat_type_ticketpage.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        seat_type_ticketpage.setText("Seat Type");

        generate_ticket_button_ticketpage.setBackground(new java.awt.Color(0, 0, 0));
        generate_ticket_button_ticketpage.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        generate_ticket_button_ticketpage.setForeground(new java.awt.Color(255, 255, 255));
        generate_ticket_button_ticketpage.setText("Genarate Ticket");
        generate_ticket_button_ticketpage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generate_ticket_button_ticketpageActionPerformed(evt);
            }
        });

        price_ticketpage.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        price_ticketpage.setText("Price");

        seat_number_ticketpage.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        seat_number_ticketpage.setText("Available Seats");

        total_price_ticketpage.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        total_price_ticketpage.setText("Total Price");

        price_ac_label_ticketpage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setText("Enter Seat Number");

        seat_number_input_jtext.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        seat_number_input_jtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat_number_input_jtextActionPerformed(evt);
            }
        });

        ok_button_train_info.setBackground(new java.awt.Color(0, 0, 0));
        ok_button_train_info.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        ok_button_train_info.setForeground(new java.awt.Color(255, 255, 255));
        ok_button_train_info.setText("OK");
        ok_button_train_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok_button_train_infoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel2.setText("AC");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel3.setText("NON AC");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(217, Short.MAX_VALUE)
                .addComponent(ticket_page_label, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(210, 210, 210))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(generate_ticket_button_ticketpage, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(total_price_ticketpage, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(total_price_label_ticketpage, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(seat_number_ticketpage, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(seat_number_ac_combo_ticketpage, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(price_ticketpage, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(price_ac_label_ticketpage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(seat_type_ticketpage, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(47, 47, 47)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(seat_number_input_jtext, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(price_nonac_label_ticketpage, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(seat_number_nonac_combo_ticketpage, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ok_button_train_info, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(129, 129, 129))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ticket_page_label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(seat_type_ticketpage, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(price_ticketpage, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(price_ac_label_ticketpage, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(price_nonac_label_ticketpage, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seat_number_ticketpage, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seat_number_ac_combo_ticketpage, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seat_number_nonac_combo_ticketpage, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seat_number_input_jtext, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ok_button_train_info, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total_price_label_ticketpage, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total_price_ticketpage, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(generate_ticket_button_ticketpage, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generate_ticket_button_ticketpageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generate_ticket_button_ticketpageActionPerformed
        this.setVisible(false);
        generate_ticket ob5= new generate_ticket();
        ob5.setVisible(true);
    }//GEN-LAST:event_generate_ticket_button_ticketpageActionPerformed

    private void seat_number_input_jtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat_number_input_jtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seat_number_input_jtextActionPerformed

    private void ok_button_train_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok_button_train_infoActionPerformed

        String url = "jdbc:sqlserver://LAPTOP-3GFO49NI\\SQLEXPRESS:1433;databaseName=RailwayBangladesh";
        String sql_user = "sqlyusha";
        String sql_password = "123456789";

        try {

            int train_no = user_home_page.send_train_number;
            String train_number = String.valueOf(train_no);
            String departure_date = user_home_page.send_date;
            int customer_id = log_in.send_CustomerId;
            Connection connection = DriverManager.getConnection(url, sql_user, sql_password);
            Statement statement = connection.createStatement();
            int count = 0, count1 = 0;
            String sql = "Select COUNT(*) AS CustomerCount from Tickets WHERE CustomerId='" + customer_id + "' AND TrainNumber = '" + train_number + "' AND DepartureDate = '" + departure_date + "'";
            ResultSet rs = statement.executeQuery(sql);

            if (rs.next()) {
                count1 = rs.getInt("CustomerCount");
            }

            if (count1 > 5) {
                JOptionPane.showMessageDialog(this, "Sorry! Ticket Purchase Limit Exceeded!");
            } else {
                String seat_number = seat_number_input_jtext.getText();

                Random ran = new Random();
                long first7 = (ran.nextLong() % 90000000L) + 5040936000000000L;
                long first8 = Math.abs(first7);
                String ticket_number = String.valueOf(first8);

                String sql1 = "Select * from Train WHERE TrainNumber = '" + train_number + "' AND DepartureDate = '" + departure_date + "'";
                ResultSet rs1 = statement.executeQuery(sql1);
                String train_name = new String();
                String source = new String();
                String destination = new String();
                String departure_time = new String();

                int fare = 0;
                if (rs1.next()) {
                    train_name = rs1.getString("TrainName");
                    source = rs1.getString("Source");
                    destination = rs1.getString("Destination");
                    departure_time = rs1.getString("DepartureTime");
                }
                String sql2 = "Select * from Seats WHERE TrainNumber = '" + train_number + "' AND DepartureDate = '" + departure_date + "' AND SeatNumber='" + seat_number + "'";
                ResultSet rs2 = statement.executeQuery(sql2);
                if (rs2.next()) {
                    fare = rs2.getInt("TicketPrice");
                }
                total_fare = total_fare + fare;

                String sql3 = "INSERT INTO Tickets Values ('" + ticket_number + "','" + customer_id + "','" + train_number + "','" + train_name + "','" + source + "','" + destination + "','" + departure_date + "','" + departure_time + "','" + seat_number + "','" + fare + "')";
                statement.executeUpdate(sql3);

                String sql4 = "Update Seats set SeatStatus='Booked' where TrainNumber = '" + train_number + "' AND DepartureDate = '" + departure_date + "' AND SeatNumber='" + seat_number + "'";
                statement.executeUpdate(sql4);

                seat_number_input_jtext.setText("");
                seat_number_input_jtext.requestFocus();

                seat_number_ac_combo_ticketpage.removeAllItems();
                seat_number_nonac_combo_ticketpage.removeAllItems();
                
                String sql5 = "SELECT * FROM Seats WHERE TrainNumber = '" + train_number + "' AND DepartureDate = '" + departure_date + "' AND SeatType ='AC' AND SeatStatus='Available'";
                ResultSet rs5 = statement.executeQuery(sql5);
                while (rs5.next()) {
                    seat_number_ac_combo_ticketpage.addItem(rs5.getString("SeatNumber"));
                }

                String sql6 = "SELECT * FROM Seats WHERE TrainNumber = '" + train_number + "' AND DepartureDate = '" + departure_date + "' AND SeatType ='NON AC' AND SeatStatus='Available'";
                ResultSet rs6 = statement.executeQuery(sql6);
                while (rs6.next()) {
                    seat_number_nonac_combo_ticketpage.addItem(rs6.getString("SeatNumber"));
                }
                
                
                total_price_label_ticketpage.setText(String.valueOf(total_fare));
                
                
                //Updating booking counter
                
                String sql7="Select * from CUSTOMER WHERE CustomerId='"+customer_id+"'";
                ResultSet rs7 = statement.executeQuery(sql7);
                int booking_count= 0;
                if(rs7.next())
                {
                    booking_count = rs7.getInt("BookingCount");
                }
                booking_count++;
                String sql8="Update CUSTOMER set BookingCount='"+booking_count+"' where CustomerId='"+customer_id+"'";
                statement.executeUpdate(sql8);

            }

        } catch (SQLException e) {
            System.out.println("database connection failed");
            e.printStackTrace();
        }


    }//GEN-LAST:event_ok_button_train_infoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ticket_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ticket_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ticket_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ticket_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ticket_info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton generate_ticket_button_ticketpage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton ok_button_train_info;
    private javax.swing.JLabel price_ac_label_ticketpage;
    private javax.swing.JLabel price_nonac_label_ticketpage;
    private javax.swing.JLabel price_ticketpage;
    private javax.swing.JComboBox<String> seat_number_ac_combo_ticketpage;
    private javax.swing.JTextField seat_number_input_jtext;
    private javax.swing.JComboBox<String> seat_number_nonac_combo_ticketpage;
    private javax.swing.JLabel seat_number_ticketpage;
    private javax.swing.JLabel seat_type_ticketpage;
    private javax.swing.JLabel ticket_page_label;
    private javax.swing.JLabel total_price_label_ticketpage;
    private javax.swing.JLabel total_price_ticketpage;
    // End of variables declaration//GEN-END:variables
}
