/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package railway.bangladesh;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import java.sql.*;

/**
 *
 * @author Yusha
 */
public class user_home_page extends javax.swing.JFrame {

    /**
     * Creates new form user_home_page
     */
    public user_home_page() {
        initComponents();
        this.setLocationRelativeTo(null); //center form in the screen
    }

    static int send_train_number;
    static String send_date = new String();

    String url = "jdbc:sqlserver://LAPTOP-3GFO49NI\\SQLEXPRESS:1433;databaseName=RailwayBangladesh";
    String sql_user = "sqlyusha";
    String sql_password = "123456789";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Month_user_combo = new javax.swing.JComboBox<>();
        Destination_user_combo = new javax.swing.JComboBox<>();
        Year_user = new javax.swing.JLabel();
        Booking_Date_user = new javax.swing.JLabel();
        Year_user_combo = new javax.swing.JComboBox<>();
        Day_user_combo = new javax.swing.JComboBox<>();
        OK_Button01_user = new javax.swing.JButton();
        Train_Name_user = new javax.swing.JLabel();
        Train_Name_user_combo = new javax.swing.JComboBox<>();
        OK_Button02_user = new javax.swing.JButton();
        User_label = new javax.swing.JLabel();
        Source_user_combo = new javax.swing.JComboBox<>();
        Date_user = new javax.swing.JLabel();
        Source_user = new javax.swing.JLabel();
        Month_user = new javax.swing.JLabel();
        Destination_user = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Month_user_combo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Month_user_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        Month_user_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Month_user_comboActionPerformed(evt);
            }
        });

        Destination_user_combo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Destination_user_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Benapole", "Chittagong", "Dhaka", "Dinajpur", "Khulna", "Kishoreganj", "Lalmonirhat", "Mymensingh", "Noakhali", "Rajshahi", "Rangpur", "Sylhet" }));
        Destination_user_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Destination_user_comboActionPerformed(evt);
            }
        });

        Year_user.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Year_user.setText("Year");

        Booking_Date_user.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Booking_Date_user.setText("Booking Date");

        Year_user_combo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Year_user_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2034", "2035", "2036", "2037", "2038", "2039", "2040" }));

        Day_user_combo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Day_user_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        Day_user_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Day_user_comboActionPerformed(evt);
            }
        });

        OK_Button01_user.setBackground(new java.awt.Color(0, 0, 0));
        OK_Button01_user.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        OK_Button01_user.setForeground(new java.awt.Color(255, 255, 255));
        OK_Button01_user.setText("OK");
        OK_Button01_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OK_Button01_userActionPerformed(evt);
            }
        });

        Train_Name_user.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Train_Name_user.setText("Available Trains");

        Train_Name_user_combo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Train_Name_user_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Train_Name_user_comboActionPerformed(evt);
            }
        });

        OK_Button02_user.setBackground(new java.awt.Color(0, 0, 0));
        OK_Button02_user.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        OK_Button02_user.setForeground(new java.awt.Color(255, 255, 255));
        OK_Button02_user.setText("OK");
        OK_Button02_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OK_Button02_userActionPerformed(evt);
            }
        });

        User_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        User_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        User_label.setText("Railway Bangladesh");

        Source_user_combo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Source_user_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Benapole", "Chittagong", "Dhaka", "Dinajpur", "Khulna", "Kishoreganj", "Lalmonirhat", "Mymensingh", "Noakhali", "Rajshahi", "Rangpur", "Sylhet" }));
        Source_user_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Source_user_comboActionPerformed(evt);
            }
        });

        Date_user.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Date_user.setText("Date");

        Source_user.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Source_user.setText("Source");

        Month_user.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Month_user.setText("Month");

        Destination_user.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Destination_user.setText("Destination");

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Show History");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Source_user, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Booking_Date_user, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Train_Name_user, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Date_user, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Day_user_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Month_user, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Train_Name_user_combo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(220, 220, 220)
                                .addComponent(Month_user_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(Year_user, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Year_user_combo, 0, 154, Short.MAX_VALUE)
                                    .addComponent(OK_Button01_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Source_user_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Destination_user, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Destination_user_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(OK_Button02_user, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(User_label, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(User_label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Source_user, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Source_user_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Destination_user, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Destination_user_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Booking_Date_user, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Day_user_combo, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(Date_user, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Month_user, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Month_user_combo, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(Year_user, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Year_user_combo, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(OK_Button01_user, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Train_Name_user, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Train_Name_user_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(OK_Button02_user, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(4, 4, 4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Month_user_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Month_user_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Month_user_comboActionPerformed

    private void Destination_user_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Destination_user_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Destination_user_comboActionPerformed

    private void Day_user_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Day_user_comboActionPerformed

    }//GEN-LAST:event_Day_user_comboActionPerformed

    private void Train_Name_user_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Train_Name_user_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Train_Name_user_comboActionPerformed

    private void Source_user_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Source_user_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Source_user_comboActionPerformed

    private void OK_Button01_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OK_Button01_userActionPerformed
        try {

            String source = (String) Source_user_combo.getSelectedItem();
            String destination = (String) Destination_user_combo.getSelectedItem();
            String day = (String) Day_user_combo.getSelectedItem();
            String month = (String) Month_user_combo.getSelectedItem();
            String year = (String) Year_user_combo.getSelectedItem();
            String d_date = day + "/" + month + "/" + year;
            send_date = d_date;

            Connection connection = DriverManager.getConnection(url, sql_user, sql_password);
            boolean flag = true;
            if (source.equals(destination)) {
                JOptionPane.showMessageDialog(this, "Invalid Input!");
            } else {
                String sql = "SELECT * FROM Train WHERE Source = '" + source + "' AND Destination = '" + destination + "' AND DepartureDate = '" + d_date + "'";
                Statement statement = connection.createStatement();
                ResultSet rs = statement.executeQuery(sql);

                while(rs.next()) {
                    Train_Name_user_combo.addItem(rs.getString("TrainName"));
                    flag = false;
                }
                if (flag) {
                    JOptionPane.showMessageDialog(this, "No Train Available!");
                }
            }

        } catch (SQLException e) {
            System.out.println("database connection failed");
            e.printStackTrace();
        }
    }//GEN-LAST:event_OK_Button01_userActionPerformed

    private void OK_Button02_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OK_Button02_userActionPerformed

        try {
            String train_name = (String) Train_Name_user_combo.getSelectedItem();

            Connection connection = DriverManager.getConnection(url, sql_user, sql_password);
            String sql2 = "SELECT TrainNumber FROM Train WHERE TrainName = '"+train_name+"'";
            Statement statement = connection.createStatement();
            ResultSet rs2 = statement.executeQuery(sql2);
            
            if(rs2.next())
            {
                send_train_number = rs2.getInt("TrainNumber");
            }

            
            
            this.setVisible(false);
            train_info ob = new train_info();
            ob.setVisible(true);

        } catch (SQLException e) {
            System.out.println("database connection failed");
            e.printStackTrace();
        }
    }//GEN-LAST:event_OK_Button02_userActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        history ob = new history();
        ob.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user_home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user_home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user_home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user_home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user_home_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Booking_Date_user;
    private javax.swing.JLabel Date_user;
    private javax.swing.JComboBox<String> Day_user_combo;
    private javax.swing.JLabel Destination_user;
    private javax.swing.JComboBox<String> Destination_user_combo;
    private javax.swing.JLabel Month_user;
    private javax.swing.JComboBox<String> Month_user_combo;
    private javax.swing.JButton OK_Button01_user;
    private javax.swing.JButton OK_Button02_user;
    private javax.swing.JLabel Source_user;
    private javax.swing.JComboBox<String> Source_user_combo;
    private javax.swing.JLabel Train_Name_user;
    private javax.swing.JComboBox<String> Train_Name_user_combo;
    private javax.swing.JLabel User_label;
    private javax.swing.JLabel Year_user;
    private javax.swing.JComboBox<String> Year_user_combo;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
